---

- name: Install rpcbind yum package
  yum:
    name: rpcbind
    state: present


- name: Set ypdomainname
  command: "ypdomainname {{ nis_domain_name }}"


- name: Set NISDOMAIN
  lineinfile:
    path: /etc/sysconfig/network
    state: present
    line: "NISDOMAIN={{ nis_domain_name }}"


- include_tasks: nis_server.yml
  when: nis_type == "server"


- include_tasks: nis_client.yml
  when: nis_type == "client"
