---

- name: Install rpcbind yum package
  ansible.builtin.dnf:
    name: rpcbind
    state: present


- name: Set ypdomainname
  ansible.builtin.command: "ypdomainname {{ nis_domain_name }}"
  changed_when: true


- name: Set NISDOMAIN
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/network
    state: present
    line: "NISDOMAIN={{ nis_domain_name }}"


- name: Configure NIS server
  ansible.builtin.include_tasks: nis_server.yml
  when: nis_type == "server"


- name: Configure NIS clients
  ansible.builtin.include_tasks: nis_client.yml
  when: nis_type == "client"
