---

- name: Install ypserv yum package
  yum:
    name: ypserv
    state: present


- name: Set yp securenets
  lineinfile:
    path: /var/yp/securenets
    state: present
    line: "{{ item }}"
    create: yes
  with_items:
    - "255.255.255.0 {{ network_ip_address.split('/')[0] }}"
    - "255.0.0.0 127.0.0.1"

    
- name: Start rpcbind service
  service:
    name: rpcbind
    state: started
    enabled: yes


- name: Start ypserv service
  service:
    name: ypserv
    state: started
    enabled: yes


- name: Start ypxfrd service
  service:
    name: ypxfrd
    state: started
    enabled: yes


- name: Start yppasswdd
  service:
    name: yppasswdd
    state: started
    enabled: yes


- name: Perform a backup of the ypinit script
  command: "cp /usr/lib64/yp/ypinit /usr/lib64/yp/ypinit.bak"


- name: Apply a patch to the ypinit script
  lineinfile:
    path: '/usr/lib64/yp/ypinit'
    regexp: '{{ item.original }}'
    line: '{{ item.new }}'
  with_items:
    - { original: 'while read h', new: 'while false' }
    - { original: 'read hostlist_ok', new: '#read hostlist_ok' }

    
- name: Set up NIS maps
  command: "/usr/lib64/yp/ypinit -m"


- name: Restore the original ypinit script
  command: "mv /usr/lib64/yp/ypinit.bak /usr/lib64/yp/ypinit"
