---

- name: Reboot the machine
  shell: 'sleep 5 && shutdown -r now "{{ reboot_msg }}"'
  async: 1
  poll: 0
  ignore_errors: True
  register: rebooting


- name: Wait for machine to come back online
  wait_for_connection:
    connect_timeout: 5
    sleep: 5
    delay: 5
    timeout: 600
  when: rebooting is changed
