---

- name: Install tigervnc-server yum package
  ansible.builtin.yum:
    name: tigervnc-server
    state: present


- name: Install x11vnc
  ansible.builtin.include_tasks: x11vnc.yml
  when: fixed_resolution_vnc


- name: Configure the VNCSERVERS
  ansible.builtin.template:
    src: vncserver@:user.service
    dest: "/etc/systemd/system/vncserver@:{{ item.value.name }}.service"
    mode: "0644"
  with_dict: "{{ users }}"
  no_log: true


- name: Stop vncserver service
  ansible.builtin.systemd:
    name: "vncserver@:{{ user.name }}.service"
    state: stopped
    enabled: true
  with_dict: "{{ users }}"
  no_log: true


- name: Run systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true


- name: Start vncserver service
  ansible.builtin.systemd:
    name: "vncserver@:{{ user.name }}.service"
    state: started
    enabled: true
  with_dict: "{{ users }}"
  no_log: true
