---

- name: Install tigervnc-server yum package
  yum:
    name: tigervnc-server
    state: present


- name: Configure the VNCSERVERS
  template:
    src: vncserver@:user.service
    dest: "/etc/systemd/system/vncserver@:{{ item.value.name }}.service"
    mode: "0644"
  with_dict: "{{ users }}"


- name: Run systemd daemon-reload
  systemd:
    daemon_reload: yes


- name: Start vncserver service
  systemd:
    name: "vncserver@:{{ user.name }}.service"
    state: restarted
    enabled: yes
