---

- set_fact:
    cfitsio_file: cfitsio3370.tar.gz
    ccfits_file: CCfits-2.4.tar.gz


- name: "Check if the cfitsio sources exists in the local repository"
  stat: path={{ local_repository_path }}/lib/{{ cfitsio_file }}
  register: cfitsio_rule


- name: "Check if the ccfits sources exist in the local repository"
  stat: path={{ local_repository_path }}/lib/{{ ccfits_file }}
  register: ccfits_rule


- name: Download cfitsio, if it does not exist in the local repo
  get_url:
    url: ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/{{ cfitsio_file }}
    dest: "{{ local_repository_path }}/lib"
  when: cfitsio_rule.stat.exists == False
  delegate_to: 127.0.0.1


- name: Download cfitsio, if it does not exist in the local repo
  get_url:
    url: http://heasarc.gsfc.nasa.gov/fitsio/CCfits-2.4/{{ ccfits_file }}
    dest: "{{ local_repository_path }}/lib"
  when: ccfits_rule.stat.exists == False
  delegate_to: 127.0.0.1


- name: Create a temporary directory for the libraries compilation
  file: path={{ remote_build_path }} state=directory
