---

- set_fact:
    discos_pwd: "{{ lookup('env', 'DISCOS_PWD') }}"

- name: Add the acs group
  become: true
  group: name=acs gid=335 state=present


- name: Create the /{{ user }} directory
  file:
    path: /{{ user }}
    state: directory
    mode: 0755


- name: Add the user {{ user }}
  become: true
  user:
    name: "{{ user }}"
    password: "{{ discos_pwd | password_hash('md5', user[:8]) }}"
    group: acs
    uid: 3060
    home: "/{{ user }}/{{ user }}"
    state: present
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa


- name: Add the user {{ user }} to sudoers
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '{{ user }}    ALL=(ALL)       ALL'

  
- file:
    path: /{{ user }}/{{ user }}/.ssh/known_hosts
    state: touch
    owner: "{{ user }}"
    group: acs
    mode: 0600


- name: Removing old public keys from known_hosts file
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: ssh-keygen -R {{ hostvars[item].ansible_host }}
  with_items: "{{ play_hosts }}"


- name: Adding new public keys to known_hosts file
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  shell: ssh-keyscan {{ hostvars[item].inventory_hostname }},{{ hostvars[item].inventory_hostname_short }},{{ hostvars[item].ansible_host }} >> /{{ user }}/{{ user }}/.ssh/known_hosts
  with_items: "{{ play_hosts }}"


- name: Sharing public key with all machines in current deployment session
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: sshpass -p {{ discos_pwd }} ssh-copy-id {{ user }}@{{ item }}
  with_items: "{{ play_hosts }}"
