---

- name: Add the acs group
  become: true
  group: name=acs gid=335 state=present


- pause:
    prompt: "Password for user {{ user }}, machine {{ ansible_hostname }}.\nWARNING: backspace key does not work in this prompt, make sure to type the password correctly (it will be asked 2 times for confirmation)"
  register: password_prompt


- fail:
    msg: "Password cannot be empty."
  when: password_prompt.user_input == ""


- pause:
    prompt: "Confirm password"
  register: password_confirm


- fail:
    msg: "Password confirmation failed."
  when: password_prompt.user_input != password_confirm.user_input


- name: Add the user {{ user }}
  become: true
  user:
    name: "{{ user }}"
    password: "{{ password_prompt.user_input | password_hash('md5', user[:8]) }}"
    group: acs
    uid: 3060
    state: present


- name: Add the user {{ user }} to sudoers
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '{{ user }}    ALL=(ALL)       ALL'
  
