---

- name: Add the acs group
  become: true
  group: name=acs gid=335 state=present


- name: Add the {{ user }} user
  become: true
  user:
    name: "{{ user }}"
    password: "{{ password }}"
    group: acs
    uid: 3060
    state: present


- name: Add the user {{ user }} to sudoers
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '{{ user }}    ALL=(ALL)       ALL'
