---

- set_fact:
    branch_path: /home/{{ user }}/{{ branch }}


- name: Remove the {{ branch_path }} directory
  become: True
  file: path={{ branch_path }} state=absent


- name: Get the DISCOS {{ branch }} repository
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: discos-get {{ branch }}
  when: branch != "master"


- name: Get the DISCOS {{ branch }} repository
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: discos-get {{ branch }} -s {{ station }}
  when: branch == "master"

- name: Increment the maximum number of user processes in order to run the AS
  become: true
  pam_limits:
    domain: discos
    limit_type: '-'
    limit_item: nproc
    value: 63266
