---

- set_fact:
    branch_path: /home/{{ user }}/branch


- name: Check if {{ branch_path }} exists
  stat: "{{ branch_path }}"
  register: branch_path


- name: get the DISCOS {{ branch }} repository
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: discos-get {{ branch }}
  when: branch_path.stat.exists == False


- name: update the repository
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: chdir={{ branch_path }} git pull
  when: branch_path.stat.exists == True
