---

- set_fact:
    branch_path: /home/{{ user }}/{{ branch }}


- name: Check if {{ branch_path }} exists
  become: true
  become_user: "{{ user }}"
  stat: path={{ branch_path }}
  register: target_path


- name: Get the DISCOS {{ branch }} repository
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: discos-get {{ branch }} -u {{ ghuser }}
  when:
    - target_path.stat.exists == False
    - branch != "master"


- name: Get the DISCOS {{ branch }} repository
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: discos-get {{ branch }} -s {{ station }} -u {{ ghuser }}
  when:
    - target_path.stat.exists == False
    - branch == "master"


- name: Pull the repository
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: chdir={{ branch_path }} git pull
  when: target_path.stat.exists == True
