---

- set_fact:
    branch_path: /home/{{ user }}/{{ branch }}-{{ station }}


- name: Remove the repository directory (if present)
  become: True
  file: path={{ branch_path }} state=absent


- name: Clone the selected DISCOS branch repository
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: discos-get {{ branch }} -s {{ station }}


- name: Set the correct CDB
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: discos-set --cdb {{ cdb }} {{ branch }}-{{ station }}
