---

- set_fact:
    gmock: { file: 'gmock-1.7.0-master.zip', build_dir: 'gmock-1.7.0-master' }

- set_fact:
    gmock_build: "{{ remote_build_path }}/{{ gmock.build_dir }}"


- name: "Check if the {{ gmock.file }}  exists in the local repository"
  stat: path={{ local_repository_path }}/lib/{{ gmock.file }}
  delegate_to: 127.0.0.1
  register: gmock_rule


- name: Download gmock (if it does not exist in the local repo)
  get_url:
    url: https://github.com/paulsapps/gmock-1.7.0/archive/master.zip
    dest: "{{ local_repository_path }}/lib"
  when: gmock_rule.stat.exists == False
  delegate_to: 127.0.0.1


- name: Create a temporary directory for the libraries compilation
  file: path={{ remote_build_path }} state=directory


- name: Copy gmock sources to the remote {{ remote_build_path }}
  unarchive:
    src={{ local_repository_path }}/lib/{{ gmock.file }}
    dest={{ remote_build_path }}


- name: Create a gmock/build directory
  file: path={{ remote_build_path }}/{{ gmock.build_dir }}/build state=directory


- name: Compile gmock
  command: chdir={{ gmock_build }}/{{ item.subdir }} {{ item.cmd }}
  with_items:
    - { cmd: 'mkdir -p build', subdir: '' }
    - { cmd: 'cmake ..', subdir: 'build' }
    - { cmd: 'make', subdir: 'build' }


- file:
    path: "{{ gmock_build }}/build/libgmock.a"
    mode: "a+x"


- file:
    path: "{{ gmock_build }}/build/libgmock_main.a"
    mode: "a+x"


- name: Copy the gmock static libraries to /usr/local/lib
  become: true
  command: chdir={{ gmock_build }}/{{ item.subdir }} {{ item.cmd }}
  with_items:
    - { cmd: 'cp -r gmock /usr/local/lib', subdir: 'include' }
    - { cmd: 'cp libgmock.a /usr/local/lib', subdir: 'build' }
    - { cmd: 'cp libgmock_main.a /usr/local/lib', subdir: 'build' }


- name: Compile gtest
  command: chdir={{ gmock_build }}/gtest/{{ item.subdir }} {{ item.cmd }}
  with_items:
    - { cmd: 'mkdir -p build', subdir: '' }
    - { cmd: 'cmake ..', subdir: 'build' }
    - { cmd: 'make', subdir: 'build' }


- file:
    path: "{{ gmock_build }}/gtest/build/libgtest.a"
    mode: "a+x"


- file:
    path: "{{ gmock_build }}/gtest/build/libgtest_main.a"
    mode: "a+x"


- name: Copy the gtest static libraries to /usr/local/lib
  become: true
  command: chdir={{ gmock_build }}/gtest/{{ item.subdir }} {{ item.cmd }}
  with_items:
    - { cmd: 'cp -r gtest /usr/local/lib', subdir: 'include' }
    - { cmd: 'cp libgtest.a /usr/local/lib', subdir: 'build' }
    - { cmd: 'cp libgtest_main.a /usr/local/lib', subdir: 'build' }


- name: Remove the directory used for the libraries compilation
  file: path={{ item }} state=absent
  with_items:
    - "{{ remote_build_path }}/{{ gmock.build_dir }}"
