---

- name: Add lustre configuration into modprobe.d
  become: True
  lineinfile:
    path: /etc/modprobe.d/lustre.conf
    line: "options lnet networks=tcp"
    state: present
    create: yes


- name: Install lustre yum packages
  become: True
  yum: name={{ item }} state=present validate_certs=no
  with_items:
    - "{{ kmod_lustre_client }}"
    - "{{ lustre_client }}"


- name: Load lustre modules
  modprobe:
    name: lnet
    state: present


- name: Add lustre modules to startup modules
  become: True
  lineinfile:
    path: /etc/sysconfig/modules/lustre.modules
    line: "{{ item }}"
    state: present
    create: yes
    mode: 0755
  with_items:
    - '#!/bin/sh'
    - ''
    - 'modprobe -v lnet'


- name: Create the lustre disk mount point if it does not exist
  become: True
  file:
    path: /mnt/discos
    state: directory
    owner: "{{ user }}"
    group: acs
    mode: 0755
  when: lustre_network_interface is defined


- name: Copy the lustre-startup script
  become: True
  template:
    src: lustre-startup
    dest: /usr/bin
    mode: 0755
    force: yes
  when: lustre_network_interface is defined


- name: Execute the lustre-startup script
  become: True
  command: lustre-startup
  when: lustre_network_interface is defined


- name: Add lustre-startup to boot executed scripts
  become: True
  lineinfile:
    path: /etc/rc.d/rc.local
    line: lustre-startup
  when: lustre_network_interface is defined
