---

- include: selinux.yml
- include: yum.yml
- include: network.yml
- include: firewall.yml
- include: ssh.yml
- include: time.yml
- include: discos_users.yml

- include: nis.yml
  when:
    - nis_domain_name is defined
    - network_ip_address is defined
    - nis_server_ip is defined
