---

- include: yum_packages.yml
- include: network_and_security.yml
- include: discos_users.yml
- include: time.yml

- include: nis.yml
  when:
    - network_domain_name is defined
    - network_ip_address is defined
    - nis_server_ip is defined
