---

- include: yum_packages.yml
- include: network.yml

- include: create_users_groups.yml
  when: discos_pwd is defined

- include: required_tools.yml
- include: acs.yml
- include: discos_dependencies.yml
- include: utilities.yml

- include: discos.yml
  when: branch is defined and station is defined and cdb is defined
