---

- include: yum_packages.yml
- include: network.yml
- include: ntp.yml

- include: nis.yml
  when: network_domain_name is defined and nis_server_ip is defined

- include: nfs.yml
  when: network_domain_name is defined and network_ip_address is defined

- include: create_discos.yml
- include: required_tools.yml
- include: acs.yml
- include: discos_dependencies.yml
- include: utilities.yml

- include: discos.yml
  when: branch is defined and station is defined and cdb is defined
