---

- include: yum_packages.yml
- include: create_users_groups.yml
- include: required_tools.yml
- include: network.yml
- include: acs.yml
- include: discos_dependencies.yml
- include: utilities.yml
- include: discos.yml
  tags: ['deploy']
