---

- include: yum_packages.yml
- include: network.yml

- include: nis.yml
  when: network_domain_name is defined and nis_server_ip is defined

- include: nfs.yml
  when: network_domain_name is defined and network_ip_address is defined

- include: ntp.yml
  when: ntp_server_ip is defined

- name: Check if DISCOS user exists on remote machine
  shell: "getent passwd {{ user }} | wc -l"
  register: is_present

- include: create_users_groups.yml
  when: is_present.stdout == "0"

- include: required_tools.yml
- include: acs.yml
- include: discos_dependencies.yml
- include: utilities.yml

- include: discos.yml
  when: branch is defined and station is defined and cdb is defined
