---

- name: Copy the hosts file template
  become: True
  template:
    src: hosts
    dest: /etc/hosts
    mode: 0644


- name: Update hostname
  hostname:
    name: "{{ inventory_hostname }}"


- name: Copy the firewall-reset template
  template:
    src: firewall-reset
    dest: "/usr/bin/"
    mode: 755
    force: yes
  become: true


- name: Add firewall-reset to startup executed scripts
  lineinfile:
    path: /etc/rc.d/rc.local
    line: firewall-reset
  become: true
