---

- name: Copy the hosts file template
  become: True
  template:
    src: hosts
    dest: /etc/hosts
    mode: 0644


- name: Update hostname
  hostname:
    name: "{{ inventory_hostname }}"


- name: Copy the firewall-reset template
  template:
    src: firewall-reset
    dest: "/usr/bin/"
    mode: 755
    force: yes
  become: true


- name: Launch the firewall-reset script
  command: firewall-reset
  become: true


- name: Configure the firewall
  service:
    name: iptables
    state: "{{ firewall_state }}"
    enabled: "{{ firewall_enabled }}"


- name: Prevent ssh to accept different localizations
  replace:
    dest: /etc/ssh/sshd_config
    regexp: '^AcceptEnv'
    replace: '# AcceptEnv'
  become: true


- name: Restart ssh service of the remote machine
  service:
    name: sshd
    state: restarted
  become: true


- name: Disable SELINUX
  selinux:
    conf: /etc/sysconfig/selinux
    state: disabled
