---

- name: Copy the hosts file template
  become: True
  template:
    src: hosts
    dest: /etc/hosts
    mode: 0644


- name: Update hostname
  hostname:
    name: "{{ inventory_hostname }}"


- name: Copy the firewall-reset template
  template:
    src: firewall-reset
    dest: "/usr/bin/"
    mode: 755
    force: yes
  become: true


- name: Launch the firewall-reset script
  command: firewall-reset
  become: true
