---

- name: Disable SELINUX
  selinux:
    state: disabled
  register: selinux_state


- name: Reboot the machine if required
  shell: 'sleep 5 && shutdown -r now "SELINUX disabled."'
  async: 1
  poll: 0
  ignore_errors: true
  when: selinux_state.reboot_required
  register: rebooting


- name: Wait for machine to come back online
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: rebooting is changed


- name: Mask firewalld service
  systemd:
    name: firewalld
    masked: yes
  when: inventory_hostname in groups['storage']


- name: Disable NetworkManager service
  service:
    name: NetworkManager
    state: stopped
    enabled: no


- name: Update hostname
  hostname:
    name: "{{ inventory_hostname }}"


- name: Copy the hosts file template
  template:
    src: hosts
    dest: /etc/hosts
    mode: 0644


- name: Copy the firewall-reset template
  template:
    src: firewall-reset
    dest: "/usr/bin/"
    mode: 755
    force: yes


- name: Launch the firewall-reset script
  command: firewall-reset
  when: firewall_state == "started"


- name: Configure the firewall
  service:
    name: iptables
    state: "{{ firewall_state }}"
    enabled: "{{ firewall_enabled }}"


- name: Prevent ssh to accept different localizations
  replace:
    dest: /etc/ssh/sshd_config
    regexp: '^AcceptEnv'
    replace: '# AcceptEnv'


- name: Restart ssh service of the remote machine
  service:
    name: sshd
    state: restarted
