---
# Pay attention, we need to install all these packages
# under the ACS environment. This means we first need
# to load the ACS environment, and then we can install
# all these packages. Also, I think all this is not
# required, because Python 2.7, shipped with ACS, already
# has unittest and pip.

- name: "Install the Python package manager"
  become: true
  shell: "{{ item }}"
  with_items:
    - wget https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py
    - rm get-pip.py


- name: "Install some third-party Python packages"
  become: true
  shell: "{{ item }}"
  with_items:
    - pip install unittest2
