---

- name: Set the timezone to UTC
  timezone:
    name: Etc/UTC


- name: Copy the ntp.conf template
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    backup: yes
  when: ntp_server_ip is defined


- name: Restart ntp service
  service:
    name: ntpd
    state: restarted
    enabled: yes


- name: Copy the plot_loopstats script
  template:
    src: plot_loopstats
    dest: /usr/local/bin/plot_loopstats
    mode: 0755
