---

- name: Copy the pyrc template
  become: True
  become_user: "{{ user }}"
  template:
    src: pyrc
    dest: /discos/{{ user }}/.pyrc
    owner: "{{ user }}"
    group: acs
    mode: 0644


- name: Install prospector (Python linter)
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: "{{ item }}"
  with_items:
    - pip install prospector==0.12.11


- name: Install ipython and create default profile
  become: true
  become_user: "{{ user }}"
  become_flags: "-i"
  command: "{{ item }}"
  with_items:
    - pip install ipython
    - ipython profile create


- name: Copy the ipython startup files
  become: True
  become_user: "{{ user }}"
  template:
    src: ipython_startup_01.py
    dest: "/discos/{{ user }}/.ipython/profile_default/startup/01.py"
    owner: "{{ user }}"
    group: acs
    mode: 0644


- name: Copy vimrc
  become: True
  become_user: "{{ user }}"
  template:
    src: vimrc
    dest: "/discos/{{ user }}/.vimrc"
    owner: "{{ user }}"
    group: acs
    mode: 0644
