---

- name: Remove yum-cron to avoid yum automatic updates
  yum:
    name: yum-cron
    state: absent


- name: Install epel-release yum package
  yum:
    name: epel-release
    state: present


- name: Install common required yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - procmail
    - vim-enhanced
    - subversion
    - unzip
    - openssl
    - screen
    - gnuplot
    - xterm
    - ksh
    - java-1.8.0-openjdk
    - ntp
    - wget
    - perl
    - net-snmp
    - rsync
    - iptables
    - rpcbind


- name: Install storage required yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - sg3_utils
    - lsof
    - attr
    - compat-openmpi16
    - lvm2
    - iptables-services
    - ypserv
  when: inventory_hostname in groups['storage']


- name: Install ACS required yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-desktop
    - gnome-desktop-devel
    - python-devel
    - gcc-c++
    - gdb
    - cmake
    - expat
    - expat-devel
    - expect
    - gsl
    - gsl-devel
    - boost
    - boost-devel
    - openssl-devel
    - ncurses-devel
    - jpackage-utils
    - ncurses
    - libtool
    - libselinux-python
    - java-1.8.0-openjdk-devel
    - curl-devel
    - perl-devel
    - gettext-devel
    - bzip2-devel
    - ypbind
    - tigervnc-server
    - firefox
    - gedit
    - bluefish
    - dejavu-sans-mono-fonts
  when: inventory_hostname in groups['acs']


- name: Install console required yum packages
  block:
    - yum:
        name: "{{ ius_release }}"
        state: present
    - yum:
        name: "{{ item }}"
        state: present
      with_items:
        - sshpass
        - python36u-pip
        - python36u-devel
        - python36u-tkinter
  when: inventory_hostname in groups['console']


- name: Install a GUI environment for ACS machines
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "@X Window System"
    - "@Desktop"
    - "@fonts"
  when: inventory_hostname in groups['acs']
