---

- name: Install all required yum packages
  become: true
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - procmail
    - vim-enhanced
    - subversion
    - python-devel
    - gcc-c++
    - gdb
    - cmake
    - ncurses
    - ncurses-devel
    - screen
    - expat
    - expat-devel
    - expect
    - gsl
    - gsl-devel
    - boost
    - boost-devel
    - gnome-desktop
    - gnome-desktop-devel
    - jpackage-utils
    - unzip
    - libtool
    - libselinux-python
    - jpackage-utils
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    - openssl
    - openssl-devel
    - curl-devel
    - perl-devel
    - gettext-devel
    - bzip2-devel
    - xterm
    - ksh
    - gnuplot
    - tigervnc-server
    - rpcbind
    - ypbind
    - nfs-utils
    - nfs4-acl-tools


- name: Install some graphical text editors
  become: true
  yum: name={{ item }} state=present
  with_items:
    - bluefish
    - gedit


- name: Install sshpass package
  become: true
  yum: name=sshpass state=present


- name: Install a GUI environment
  become: true
  yum: name={{ item }} state=present
  with_items:
    - "@X Window System"
    - "@Desktop"
    - "@fonts"


- name: Apply a patch to GNOME in order to avoid an annoying VNC popup
  become: True
  lineinfile:
    path: /etc/xdg/autostart/gpk-update-icon.desktop
    line: X-GNOME-Autostart-enabled=false
    state: present


- name: "To avoid yum automatic updates, remove yum-cron"
  become: true
  yum: name=yum-cron state=absent
