---

- name: Install correct java yum packages
  ansible.builtin.yum:
    name:
      - java-11-openjdk
      - java-11-openjdk-headless
      - java-11-openjdk-devel
    state: present


- name: Fetch the installed yum packages
  ansible.builtin.yum:
    list: installed
  register: package_facts


- name: Filter OpenJDK packages to be removed (non-Java 11)
  ansible.builtin.set_fact:
    openjdk_packages_to_remove: "{{ package_facts.results |
                                    selectattr('name', 'match', '^java-[^-]+-openjdk(-(headless|devel))?$') |
                                    selectattr('name', 'search', '^(?!java-11-openjdk)') |
                                    map(attribute='name') | list }}"


- name: Uninstall OpenJDK packages different from Java 11
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ openjdk_packages_to_remove }}"
