---

- include: yum.yml
- include: git.yml
- include: discos_environment.yml
- include: acs.yml
- include: discos_dependencies.yml
- include: utilities.yml
- include: receivers_monitor.yml
  when:
    - monitor_receivers == True
