---

- name: Install ACS yum packages
  ansible.builtin.include_tasks: yum.yml


- name: Configure the DISCOS environment
  ansible.builtin.include_tasks: discos_environment.yml


- name: Install ACS
  ansible.builtin.include_tasks: acs.yml


- name: Install the DISCOS dependencies
  ansible.builtin.include_tasks: discos_dependencies.yml


- name: Install some utilities
  ansible.builtin.include_tasks: utilities.yml


- name: Configure the monitoring for the receivers
  ansible.builtin.include_tasks: receivers_monitor.yml
  when: monitor_receivers
