---

- name: Create the /service/receivers directory
  file:
    path: "/service/receivers"
    state: directory
    owner: "{{ user.name }}" 
    group: "{{ user.group }}"
    mode: 0755
    recurse: True


- name: Add receivers monitoring script to rc.local 
  blockinfile:
    path: "/etc/rc.local"
    state: present
    marker: "######## Receivers monitoring {mark} ########"
    block: |
        if [ -f /{{ discos_sw_dir }}/introots/default/bin/receiversmonitor.py ]; then
            runuser -l {{ user.name }} -c 'receiversmonitor.py &'
        fi
