---

- name: Create the /service/receivers directory
  ansible.builtin.file:
    path: "/service/receivers"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"
    recurse: true


- name: Add receivers monitoring script to rc.local
  ansible.builtin.blockinfile:
    path: "/etc/rc.local"
    state: present
    marker: "######## Receivers monitoring {mark} ########"
    block: |
        if [ -f /{{ discos_sw_dir }}/introots/default/bin/receiversmonitor.py ]; then
            runuser -l {{ user.name }} -c 'receiversmonitor.py &'
        fi
