---

- name: Configure the VNCSERVERS
  lineinfile:
    path: /etc/sysconfig/vncservers
    line: 'VNCSERVERS="1:{{ user }}"'
    regexp: '^VNCSERVERS=(.*)$'
    state: present


- name: Configure VNCSERVERARGS
  lineinfile:
    path: /etc/sysconfig/vncservers
    line: 'VNCSERVERARGS[1]="-name {{ inventory_hostname_short }}-{{ user }} -localhost -SecurityTypes None -geometry {{ vnc_resolution }} -depth 32 -AlwaysShared -nolisten tcp -rfbport {{ vnc_starting_port+user_vnc_port|int }}"'
    state: present


- name: Enable ssh tunneling for {{ user }} only for the VNCSERVER port
  blockinfile:
    path: "/etc/ssh/sshd_config"
    state: present
    marker: "##### {{ user }} port forwarding configuration {mark} #####"
    block: |
        Match User {{ user }}
            PermitOpen localhost:{{ vnc_starting_port+user_vnc_port|int }}


- block:
  - name: Add the {{ observer }} VNCSERVER
    lineinfile:
      path: /etc/sysconfig/vncservers
      regexp: '^VNCSERVERS=(.*)$'
      line: 'VNCSERVERS="1:{{ user }} 2:{{ observer }}"'
  - name: Configure the {{ observer }} VNCSERVERARGS
    lineinfile:
      path: /etc/sysconfig/vncservers
      line: 'VNCSERVERARGS[2]="-name {{ inventory_hostname_short }}-{{ observer }} -localhost -SecurityTypes None -geometry {{ vnc_resolution }} -depth 32 -AlwaysShared -nolisten tcp -rfbport {{ vnc_starting_port+observer_vnc_port|int }}"'
      state: present
  - name: Enable ssh tunneling for user {{ observer }} only for the VNCSERVER port
    blockinfile:
      path: "/etc/ssh/sshd_config"
      state: present
      marker: "##### {{ observer }} port forwarding configuration {mark} #####"
      block: |
          Match User {{ observer }}
              PermitOpen localhost:{{ vnc_starting_port+observer_vnc_port|int }}
  when: inventory_hostname in groups['console']


- name: Restart ssh service
  service:
    name: sshd
    state: restarted
    enabled: yes


- name: Apply a patch to GNOME in order to avoid an annoying VNC popup
  lineinfile:
    path: /etc/xdg/autostart/gpk-update-icon.desktop
    line: X-GNOME-Autostart-enabled=false
    state: present


- name: Start vncserver service
  service:
    name: vncserver
    state: started
    enabled: yes
