---

- name: Apply a common configuration to tigervnc-server
  lineinfile:
    path: /etc/sysconfig/vncservers
    line: "{{ item }}"
    state: present
  with_items:
    - 'VNCSERVERS="1:{{ user }}"'
    - 'VNCSERVERARGS[1]="-name {{ inventory_hostname }}-{{ user }} -localhost -SecurityTypes None -geometry {{ vnc_resolution }} -depth 32 -AlwaysShared -nolisten tcp -rfbport {{ vnc_starting_port+user_vnc_port|int }}"'


- name: Configure tigervnc-server for the console machine
  block:
    - replace:
        path: /etc/sysconfig/vncservers
        regexp: '^VNCSERVERS="1:{{ user }}"$'
        replace: 'VNCSERVERS="1:{{ user }} 2:{{ observer }}"'
    - lineinfile:
        path: /etc/sysconfig/vncservers
        line: 'VNCSERVERARGS[2]="-name {{ inventory_hostname }}-{{ observer }} -localhost -SecurityTypes None -geometry {{ vnc_resolution }} -depth 32 -AlwaysShared -nolisten tcp -rfbport {{ vnc_starting_port+observer_vnc_port|int }}"'
        state: present
    - blockinfile:
        path: "/etc/ssh/sshd_config"
        state: present
        marker: "##### {{ observer }} port forwarding configuration {mark} #####"
        block: |
            Match User {{ observer }}
                PermitOpen localhost:{{ vnc_starting_port+observer_vnc_port|int }}
  when: inventory_hostname in groups['console']


- name: Apply a patch to GNOME in order to avoid an annoying VNC popup
  lineinfile:
    path: /etc/xdg/autostart/gpk-update-icon.desktop
    line: X-GNOME-Autostart-enabled=false
    state: present


- name: Restart ssh service
  service:
    name: sshd
    state: restarted
    enabled: yes


- name: Start vncserver service
  service:
    name: vncserver
    state: started
    enabled: yes
