---

- name: Download {{ ds9 }} archive
  get_url:
    url: "{{ remote_repository_download_url }}/{{ ds9 }}"
    dest: "{{ local_repository_path }}"
    force: false
    headers:
      Authorization: "token {{ repository_token }}"
  delegate_to: localhost
  run_once: true


- name: Extract the {{ ds9 }} archive to the remote
  unarchive:
    src: "{{ local_repository_path }}/{{ ds9 }}"
    dest: "/usr/bin/"
    mode: 0755
