---

- name: Install quicklook python dependencies
  ansible.builtin.command: "pip install {{ item }}"
  become: true
  become_user: "{{ user.name }}"
  become_flags: "-i"
  with_items:
    - watchdog
    - tornado
  changed_when: true


- name: Copy the quicklook service unit file
  ansible.builtin.template:
    src: quicklook.service
    dest: /usr/lib/systemd/system/quicklook.service
    mode: "0644"
    force: true


- name: Create the quicklook directory
  ansible.builtin.file:
    path: "/{{ discos_sw_dir }}/quicklook"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"


- name: Copy the quicklook configuration file
  ansible.builtin.template:
    src: "monitor_config.ini"
    dest: "/{{ discos_sw_dir }}/quicklook"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0640"
    force: true


- name: Start the quicklook service
  ansible.builtin.systemd:
    name: "quicklook.service"
    state: restarted
    enabled: true
