---

- name: Create the basie directories
  file:
    path: /{{ discos_sw_dir }}/basie
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700


- name: Copy the basie-get template
  template:
    src: basie-get
    dest: /{{ discos_sw_dir }}/basie/
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700
    force: true


- name: Execute the basie-get script
  command: ./basie-get -b
  args:
    chdir: /{{ discos_sw_dir }}/basie/
