---

- name: Download the BASIE repository
  ansible.builtin.git:
    repo: "https://github.com/discos/basie.git"
    dest: "/{{ discos_sw_dir }}/basie"
    version: "master"
    force: true
  become: true
  become_user: "{{ user.name }}"


- name: Install BASIE
  ansible.builtin.command: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  become_flags: "-i"
  with_items:
    - "pip install -r requirements.txt"
    - "pip install ."
    - "pyenv rehash"
  args:
    chdir: "/{{ discos_sw_dir }}/basie/"
  changed_when: true
