---

- name: Install BASIE Python dependencies
  command: "pip install {{ item }}"
  with_items:
    - astropy==2.0.8
    - persistent==4.4.2
  become: True
  become_user: "{{ user.name }}"
  become_flags: "-i"
