---

- name: Install epel-release yum package
  yum:
    name: epel-release
    state: present


- name: Install xdotool package
  yum:
    name: xdotool
    state: present


- name: Copy the maximize_left and maximize_right scripts
  template:
    src: "{{ item }}"
    dest: /usr/bin
    mode: 0755
    force: yes
  with_items:
    - maximize_left
    - maximize_right


- name: Make sure keybindings gconf path exists
  file:
    path: "/{{ discos_sw_dir }}/{{ item[0].value.name }}/.gconf/desktop/{{ item[1].path }}"
    state: "{{ item[1].state }}"
    owner: "{{ item[0].value.name }}"
  no_log: True
  with_nested:
    - "{{ users | dict2items }}"
    - "{{ paths }}" 
  vars:
    paths:
      - { path: "gnome/keybindings/custom0", state: directory }
      - { path: "gnome/keybindings/custom1", state: directory }
      - { path: "gnome/keybindings/%gconf.xml", state: touch }
      - { path: "gnome/%gconf.xml", state: touch }
      - { path: "%gconf.xml", state: touch }


- name: Copy the keybindings files
  template:
    src: "gconf.xml"
    dest: "/{{ discos_sw_dir }}/{{ item[0].value.name }}/.gconf/desktop/gnome/keybindings/{{ item[1].dest }}/%gconf.xml"
    owner: "{{ item[0].value.name }}"
    force: yes
  no_log: True
  with_nested:
    - "{{ users | dict2items }}"
    - "{{ paths }}"
  vars:
    paths:
      - { side: "Left", dest: "custom0" }
      - { side: "Right", dest: "custom1" }
