---

- name: Install iptables yum packages
  ansible.builtin.dnf:
    name: "{{ firewall_packages }}"
    state: present


- name: Mask firewalld service
  ansible.builtin.systemd:
    name: firewalld
    masked: true
  failed_when: false


- name: Copy the firewall-reset template
  ansible.builtin.template:
    src: firewall-reset
    dest: "/usr/bin/"
    mode: "0755"
    force: true


- name: Launch the firewall-reset script
  ansible.builtin.command: firewall-reset
  when: firewall_state == "started"
  changed_when: true


- name: Configure the firewall
  ansible.builtin.systemd:
    name: iptables
    state: "{{ firewall_state }}"
    enabled: "{{ firewall_enabled }}"
