#!/usr/bin/env bash

# Useful aliases
# ==============
alias l='ls'
alias ll='ls -la'
alias la='ls -A'
alias lt='ls -lt | more'

# Variables to export
# ===================
export QTDIR={{ qt_dir }}
export QTLIB=$QTDIR/lib
export QTINC=/usr/include/Qt
export qt_prefix=$QTLIB
export PATH=$PATH:$QTDIR/bin:$HOME/.local/bin:$HOME/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/lib64/:/usr/lib64:$QTLIB
export PYTHONSTARTUP=$HOME/.pyrc
export EDITOR=vi

# Update the pyenv shims in order to be able to use newly installed python packages
# =================================================================================
pyenv rehash > /dev/null 2>&1

{% if inventory_hostname not in groups['manager'] %}
# ACS Manager reference
# =====================
MNG_IP={{ hostvars[groups['manager'].0].ansible_host }}
export MANAGER_REFERENCE=corbaloc::$MNG_IP:3000/Manager

{% endif %}
# Update the environment now and with every prompt
# ================================================
PROMPT_COMMAND='source /{{ discos_sw_dir }}/config/misc/prompt_command.sh'
$PROMPT_COMMAND
