---

- name: Create the sdtools directory
  file:
    path: "/{{ discos_sw_dir }}/sdtools"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0710


- name: Copy the sdtools-get template
  template:
    src: sdtools-get
    dest: "/{{ discos_sw_dir }}/sdtools/"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700
    force: true


- name: Execute the sdtools-get script
  command: ./sdtools-get -b
  args:
    chdir: "/{{ discos_sw_dir }}/sdtools/"
