---

- name: Install SDTools required yum packages
  yum:
    name:
      - llvm
      - python36u-pip
      - python36u-devel
      - python36u-tkinter
    state: present


- name: Upgrade pip3.6 to latest version
  command: "{{ item }}"
  with_items:
    - "easy_install-3.6 -U pip"


- name: Install SDTools python dependencies
  command: "pip3.6 install {{ item }}"
  with_items:
    - astropy
    - numpy
    - scipy
    - matplotlib
    - pyyaml
    - h5py
    - statsmodels
    - numba==0.50.1
    - watchdog
