---

- name: Install NetworkManager yum package
  ansible.builtin.dnf:
    name: NetworkManager
    state: present


- name: Disable NetworkManager service
  ansible.builtin.service:
    name: NetworkManager
    state: stopped
    enabled: false


- name: Update hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"


- name: Copy the hosts file template
  ansible.builtin.template:
    src: hosts
    dest: /etc/hosts
    mode: "0644"


- name: Tune the host searching order
  ansible.builtin.lineinfile:
    dest: /etc/host.conf
    state: present
    line: "order hosts,bind"


- name: Install the dnsmasq yum package
  ansible.builtin.dnf:
    name: dnsmasq
    state: present


- name: Copy the resolv.conf template
  ansible.builtin.template:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: "0644"
    force: true


- name: Copy the resolv.dnsmasq template
  ansible.builtin.template:
    src: resolv.dnsmasq
    dest: /etc/resolv.dnsmasq
    mode: "0644"
    force: true


- name: Copy the dnsmasq.conf template
  ansible.builtin.template:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    mode: "0644"
    force: true


- name: Start and enable the dnsmasq service
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
    enabled: true
