---

- name: Install NetworkManager yum package
  ansible.builtin.yum:
    name: NetworkManager
    state: present


- name: Disable NetworkManager service
  ansible.builtin.service:
    name: NetworkManager
    state: stopped
    enabled: false
    use: systemd


- name: Update hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when: ansible_virtualization_type != 'docker'


- name: Copy the hosts file template
  ansible.builtin.template:
    src: hosts
    dest: /etc/hosts
    mode: "0644"
    unsafe_writes: true


- name: Tune the host searching order
  ansible.builtin.lineinfile:
    dest: /etc/host.conf
    state: present
    line: "order hosts,bind"


- name: Copy the resolv.conf template
  ansible.builtin.template:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: "0644"
    force: true
    unsafe_writes: true
  when: ansible_virtualization_type != 'docker'


- name: Configure dnsmasq
  ansible.builtin.include_tasks: dnsmasq.yml
  when: ansible_virtualization_type != 'docker'
