---

- name: Create the local repository
  ansible.builtin.file:
    path: "{{ local_repository_path }}"
    state: directory
    mode: "0755"
  delegate_to: localhost
  run_once: true


- name: Fetch the repository token value
  ansible.builtin.set_fact:
    repository_token: "{{ lookup('ansible.builtin.env', 'REPOSITORY_TOKEN', default='') }}"
  no_log: true


- name: Retrieve the token from the discos/dependencies repository
  ansible.builtin.include_tasks: retrieve.yml
  when: repository_token == ""
