---
- name: Remove old version of git
  yum:
    name: 
        - git-all
        - git-core
    state: absent


- name: Install git 2 from IUS
  yum:
    name:
      - git2u-all


- name: Check if the token for the dependencies repository is missing
  stat:
    path: "{{ local_repository_path }}/token/token"
  register: token_present


- name: Delete the eventual token directory in case the token is missing
  file:
    path: "{{ local_repository_path }}/token"
    state: absent
  when: token_present.stat.exists == False


- name: Download the repository token
  git:
    repo: "{{ remote_repository_clone_url }}"
    dest: "{{ local_repository_path }}/token"
    force: True
    depth: 1
  when: token_present.stat.exists == False


- name: Fetch the repository token value
  set_fact:
    repository_token: "{{ item }}"
  with_file: "{{ local_repository_path }}/token/token"
  no_log: True
