---

- name: Gather network interfaces list
  shell: ifconfig -a | sed 's/[ :].*//;/^\(lo\|\)$/d'
  register: network_interfaces


- name: Parse the network interfaces list
  set_fact:
    network_interfaces: "{{ network_interfaces.stdout.split('\n') }}"


- name: Check if lustre_network_interface is listed
  fail:
    msg: "Interface {{ lustre_network_interface }} not present in the system! Choose among {{ ', '.join(network_interfaces) }}"
  when: lustre_network_interface not in network_interfaces
