---

- name: Copy lustre client packages to the remote
  copy:
    src: "{{ local_repository_path }}/{{ item }}-{{ lustre_client_tail }}"
    dest: "/tmp/"
  with_items: "{{ lustre_client_files }}"


- name: Install lustre yum packages
  yum:
    name: "{{ lustre_client_files | map('regex_replace', '(.*)', '/tmp/\\1-' + lustre_client_tail) | list }}"
    state: present
    validate_certs: no


- name: Delete lustre packages from the remote
  file:
    path: "/tmp/{{ item }}-{{ lustre_client_tail }}"
    state: absent
  with_items: "{{ lustre_client_files }}"


- name: Add lustre configuration into modprobe.d
  lineinfile:
    path: /etc/modprobe.d/lustre.conf
    line: "options lnet networks=tcp"
    state: present
    create: yes


#- name: Load lustre modules
#  modprobe:
#    name: lnet
#    state: present
# Workaround to avoid a known Ansible bug introduced in v2.8
- name: Load lustre modules
  command: "modprobe -v lnet"


- name: Add lustre modules to startup modules
  lineinfile:
    path: /etc/sysconfig/modules/lustre.modules
    line: "{{ item.line }}"
    state: present
    create: yes
    mode: 0755
    insertbefore: "{{ item.before }}"
  with_items:
    - { line: '#!/bin/sh', before: "BOF" }
    - { line: 'modprobe -v lnet', before: "" }


- name: Copy the lustre-client-service template
  template:
    src: lustre-client-service
    dest: /etc/rc.d/init.d/lustre
    mode: 0755
    force: yes


- name: Configure the clients lustre service
  file:
    src: /etc/rc.d/init.d/lustre
    dest: "/etc/rc.d/{{ item }}"
    state: link
    force: true
  with_items:
    - "rc0.d/K05lustre"
    - "rc3.d/S95lustre"
