---

- name: Copy lustre client packages to the remote
  ansible.builtin.copy:
    src: "{{ local_repository_path }}/{{ item }}-{{ lustre_client_tail }}"
    dest: "/tmp/"
    mode: "0644"
  with_items: "{{ lustre_client_files }}"


- name: Install lustre yum packages
  ansible.builtin.dnf:
    name: "{{ lustre_client_files | map('regex_replace', '(.*)', '/tmp/\\1-' + lustre_client_tail) | list }}"
    state: present
    validate_certs: false


- name: Delete lustre packages from the remote
  ansible.builtin.file:
    path: "/tmp/{{ item }}-{{ lustre_client_tail }}"
    state: absent
  with_items: "{{ lustre_client_files }}"


- name: Add lustre configuration into modprobe.d
  ansible.builtin.lineinfile:
    path: "/etc/modprobe.d/lustre.conf"
    line: "options lnet networks=tcp"
    state: present
    create: true
    mode: "0644"


- name: Load lustre modules
  ansible.builtin.command: "modprobe -v lnet"
  changed_when: true


- name: Add lustre modules to startup modules
  ansible.builtin.lineinfile:
    path: "/etc/sysconfig/modules/lustre.modules"
    line: "{{ item.line }}"
    state: present
    create: true
    mode: "0755"
    insertbefore: "{{ item.before }}"
  with_items:
    - { line: '#!/bin/sh', before: "BOF" }
    - { line: 'modprobe -v lnet', before: "" }


- name: Copy the lustre-client-service template
  ansible.builtin.template:
    src: lustre-client-service
    dest: "/etc/rc.d/init.d/lustre"
    mode: "0755"
    force: true


- name: Configure the clients lustre service
  ansible.builtin.file:
    src: "/etc/rc.d/init.d/lustre"
    dest: "/etc/rc.d/{{ item }}"
    state: link
    force: true
  with_items:
    - "rc0.d/K05lustre"
    - "rc3.d/S95lustre"
