---

- include: check_interfaces.yml

- include: check_dependencies.yml
  delegate_to: localhost
  run_once: true

- include: lustre_clients.yml
  when: lustre_type == "client"

- block:
  - name: Check if lustre is already configured on server
    stat:
      path: /usr/lib/systemd/system/lustre.service
    register: lustre_configured
  - include: lustre_server.yml
    when: not lustre_configured.stat.exists
  when: lustre_type == "server"
