---

- name: Build the discos-get Ansible command
  set_fact:
    repo_name: "{{ branch }}{{ '-' + station|lower if inventory_dir.split('/')[-1] == 'development' else '' }}"
    discos_get_cmd: "discos-get -b {{ branch }}{{ ' -s ' + station|lower if inventory_dir.split('/')[-1] == 'development' else '' }}"

- debug:
    var: discos_get_cmd

- debug:
    var: repo_name
  failed_when: True


- name: Define the sources and introot directory for DISCOS repository
  set_fact:
    sources_path: "/{{ discos_sw_dir }}/{{ user.name }}/{{ repo_name }}"
    introot_path: "/{{ discos_sw_dir }}/introots/{{ repo_name }}"


- name: Remove the repository directory and introot (if present)
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ sources_path }}"
    - "{{ introot_path }}"


- name: Clone the selected DISCOS branch repository
  command: "{{ discos_get_cmd }}"
  become: True
  become_user: "{{ user.name }}"
  become_flags: "-i"


- name: Set the correct CDB
  command: "discos-set --cdb {{ cdb }} {{ repo_name }}"
  become: True
  become_user: "{{ user.name }}"
  become_flags: "-i"


- name: Install DISCOS
  shell: "{{ item }}"
  with_items:
    - make
    - make install
  args:
    chdir: "{{ sources_path }}/SystemMake"
  become: True
  become_user: "{{ user.name }}"
  become_flags: "-i"
