---

- name: Build the discos-get Ansible command
  ansible.builtin.set_fact:
    repo_name: "{{ branch }}{{ '-' + station | lower if inventory_dir.split('/')[-1] == 'development' else '' }}"
    discos_get_cmd: "discos-get {{ branch }}{{ ' -s ' + station if inventory_dir.split('/')[-1] == 'development' else '' }}"


- name: Define the sources and introot directory for DISCOS repository
  ansible.builtin.set_fact:
    sources_path: "/{{ discos_sw_dir }}/{{ user.name }}/{{ repo_name }}"
    introot_path: "/{{ discos_sw_dir }}/introots/{{ repo_name }}"


- name: Remove the repository directory and introot (if present)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ sources_path }}"
    - "{{ introot_path }}"


- name: Clone the selected DISCOS branch repository
  ansible.builtin.command: "{{ discos_get_cmd }}"
  become: true
  become_user: "{{ user.name }}"
  become_flags: "-i"
  changed_when: true


- name: Set the correct CDB
  ansible.builtin.command: "discos-set --cdb {{ cdb }} {{ repo_name }}"
  become: true
  become_user: "{{ user.name }}"
  become_flags: "-i"
  changed_when: true


- name: Build and install DISCOS
  ansible.builtin.command: "make -j"
  args:
    chdir: "{{ sources_path }}/SystemMake"
  become: true
  become_user: "{{ user.name }}"
  become_flags: "-i"
  changed_when: true
