#!/usr/bin/env python
"""Some command line examples:

  $ discos-login manager
  $ discos-login -u root manager
  $ discos-login -u observer console
"""
import subprocess
from argparse import ArgumentParser
import deployment

parser = ArgumentParser()
parser.add_argument(
    '-u', '--user',
    required=False,
    default='discos'
)
parser.add_argument('machine', choices=deployment.machineList())
args = parser.parse_args()

if deployment.isRunning(args.machine):
    try:
        subprocess.call([
            'ssh',
            '-X',
            '-l',
            args.user,
            deployment.getIp(args.machine)
        ])
    except KeyboardInterrupt:
        pass
else:
    print('Machine {} is not running.'.format(args.machine))
