---

- name: Create the basie directories
  file:
    path: /{{ discos_sw_dir }}/basie
    state: directory
    owner: "{{ user }}"
    group: acs
    mode: 0700


- name: Install the basie dependencies
  command: "pip2.7 install {{ item }}"
  with_items:
    - astropy==2.0.8
    - persistent==4.4.2


- name: Copy the basie-get template
  template:
    src: basie-get
    dest: /{{ discos_sw_dir }}/basie/
    owner: "{{ user }}"
    group: acs
    mode: 0700
    force: true


- name: Execute the basie-get script
  command: ./basie-get
  args:
    chdir: /{{ discos_sw_dir }}/basie/
