---

- name: Install basie dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python27
    - python27-pip


- name: Create the basie directories
  file:
    path: /discos/basie
    state: directory
    owner: "{{ user }}"
    group: acs
    mode: 0700


- name: Copy the basie-get template
  template:
    src: basie-get
    dest: /discos/basie/
    owner: "{{ user }}"
    group: acs
    mode: 0700
    force: true


- name: Execute the basie-get script
  command: ./basie-get
  args:
    chdir: /discos/basie/
