---

- name: Copy the quicklook service template
  template:
    src: quicklook
    dest: /etc/rc.d/init.d/quicklook
    mode: 0755
    force: true


- name: Create the sdtools/quicklook directory
  file:
    path: "/{{ discos_sw_dir }}/sdtools/quicklook"
    state: directory
    owner: "{{ user }}"
    group: acs
    mode: 0750


- name: Copy the quicklook configuration files
  template:
    src: "{{ item }}"
    dest: "/{{ discos_sw_dir }}/sdtools/quicklook/"
    owner: "{{ user }}"
    group: acs
    mode: 0640
    force: true
  with_items:
    - "monitor_config.ini"
    - "service.conf"


- name: Make sure the Desktop directory exists for {{ observer }}
  file:
    path: "/{{ discos_sw_dir }}/{{ observer }}/Desktop"
    state: directory
    owner: "{{ observer }}"
    group: acs
    mode: 0755


- name: Create a link to the quicklook index.html page
  file:
    src: "/{{ discos_sw_dir }}/sdtools/quicklook/index.html"
    dest: "/{{ discos_sw_dir }}/{{ observer }}/Desktop/quicklook.html"
    state: link
    force: true
    owner: "{{ user }}"
    group: acs
    mode: 0644
