---

- name: Install SDTools dependencies
  command: "pip3.6 install {{ item }}"
  with_items:
    - astropy
    - numpy
    - scipy
    - matplotlib
    - pyyaml
    - h5py
    - statsmodels
    - numba
    - watchdog
    - Zdaemon


- name: Create the sdtools directory
  file:
    path: "/{{ discos_sw_dir }}/sdtools"
    state: directory
    owner: "{{ user }}"
    group: acs
    mode: 0710


- name: Copy the sdtools-get template
  template:
    src: sdtools-get
    dest: "/{{ discos_sw_dir }}/sdtools/"
    owner: "{{ user }}"
    group: acs
    mode: 0700
    force: true


- name: Execute the sdtools-get script
  command: ./sdtools-get -b
  args:
    chdir: "/{{ discos_sw_dir }}/sdtools/"
