---

- name: Install SELINUX python bindings
  ansible.builtin.yum:
    name: python3-libselinux
    state: present


- name: Disable SELINUX
  ansible.posix.selinux:
    state: disabled
  register: selinux_state


- name: Reboot the machine if required
  ansible.builtin.reboot:
    msg: 'SELINUX disabled.'
  when: selinux_state.reboot_required
