---

- name: Install SELINUX python bindings
  yum:
    name: python3-libselinux
    state: present


- name: Disable SELINUX
  selinux:
    state: disabled
  register: selinux_state


- name: Reboot the machine if required
  reboot:
    msg: 'SELINUX disabled.'
  when: selinux_state.reboot_required
