---

- name: Install SELINUX python bindings
  yum:
    name: libselinux-python
    state: present


- name: Disable SELINUX
  selinux:
    state: disabled
  register: selinux_state


- name: Reboot the machine if required
  include_role:
    name: reboot
  vars:
    reboot_msg: 'SELINUX disabled.'
  when: selinux_state.reboot_required
