---

- name: Before starting the deployment, apply local tasks
  hosts: all
  tasks:
    - name: Create a local directory to be used as a repository
      file:
        path: "{{ local_repository_path }}"
        state: directory
      delegate_to: localhost
      run_once: true


- name: Apply common configurations to all nodes
  hosts: all
  remote_user: root
  roles:
    - common


- name: Configure lustre
  hosts: all
  remote_user: root
  roles:
    - lustre


- name: Apply ACS configuration to ACS nodes
  hosts: acs
  remote_user: root
  roles:
    - acs


- name: Configure the manager machine
  hosts: manager
  remote_user: root
  roles:
    - manager


- name: Configure the console machine
  hosts: console
  remote_user: root
  roles:
    - console


- name: Deploy DISCOS
  hosts: acs
  remote_user: root
  roles:
    - deploy


- name: Finalize the installation
  hosts: all
  remote_user: root
  roles:
    - finalize
