---

- name: Before starting the deployment, apply local tasks
  hosts: all
  tasks:
    - name: Create a local directory to be used as a repository
      file:
        path: "{{ local_repository_path }}"
        state: directory
      delegate_to: 127.0.0.1
      run_once: true


- name: Apply common configurations to all nodes
  hosts: all
  remote_user: root
  roles:
    - common


- name: Apply ACS configuration to ACS nodes
  hosts: acs
  remote_user: root
  roles:
    - acs


- name: Configure the manager
  hosts: manager
  remote_user: root
  roles:
    - manager


- name: Configure the console
  hosts: console
  remote_user: root
  roles:
    - console


- name: Deploy DISCOS
  hosts: acs
  remote_user: root
  roles:
    - deploy


- name: Remove the provisioning machine public key from provisioned hosts
  hosts: all
  remote_user: root
  tasks:
    - file:
        path: /root/.ssh
        state: absent
