---

- name: Before starting the deployment, apply local tasks
  hosts: all
  tasks:
    - name: Create a local directory to be used as a repository
      local_action: file  path={{ local_repository_path }} state=directory


- name: Apply common configurations to all nodes
  hosts: all
  remote_user: root
  roles:
    - common


- name: Configure the manager
  hosts: manager
  remote_user: "{{ user }}"
  roles:
    - manager


- name: Delete the provisioning machine public key from provisioned hosts
  hosts: all
  remote_user: root
  tasks:
    - file: path=/root/.ssh state=absent
