---

- name: Before starting the deployment, apply local tasks
  hosts: local
  tasks:
    - name: Create a local directory to be used as a repository
      file: path={{ local_repository_path }} state=directory


- name: Apply common configurations to all nodes
  hosts: all
  remote_user: root
  roles:
    - common


- name: Configure the manager
  hosts: discos-mng
  remote_user: "{{ user }}"
  roles:
    - manager
