---

- name: Create a local directory to be used as a repository
  file: path={{ local_repository_path }} state=directory
  delegate_to: 127.0.0.1


# This playbook deploys the whole application stack.

- name: Apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

# - name: configure the manager
#   hosts: manager
#   remote_user: root
#
#   roles:
#     - idonotknow
