---

- name: Delete any OS welcome message
  ansible.builtin.command: "truncate -s 0 /etc/motd"
  changed_when: true


- name: Fetch the local user's public key
  ansible.builtin.command: "cat ~/.ssh/id_rsa.pub"
  register: local_public_key
  delegate_to: localhost
  run_once: true
  changed_when: false


- name: Remove the local user's public key from remote .ssh/authorized_hosts file
  ansible.builtin.lineinfile:
    path: "~/.ssh/authorized_keys"
    line: "{{ local_public_key.stdout }}"
    state: absent


- name: Remove the remote repository token
  ansible.builtin.file:
    path: "{{ local_repository_path }}/token"
    state: absent
  delegate_to: localhost
  run_once: true


- name: Remove the temporary directory used for libraries compilation
  ansible.builtin.file:
    path: "{{ remote_build_path }}"
    state: absent
