---

- name: Render the discos-addProject template
  become: True
  become_user: "{{ user }}"
  template:
    src: discos-addProject
    dest: "/{{ user }}/{{ user }}/bin/"
    owner: "{{ user }}"
    group: acs
    mode: 0544
    force: yes


- name: Render the discos-removeProject template
  become: True
  become_user: "{{ user }}"
  template:
    src: discos-removeProject
    dest: "/{{ user }}/{{ user }}/bin/"
    owner: "{{ user }}"
    group: acs
    mode: 0544
    force: yes


- name: Copy the bashrc template into /etc/skel
  become: True
  template:
    src: bashrc
    dest: /etc/skel/.bashrc
    owner: root
    group: root
    mode: 0644
    force: yes


- name: Copy the bash_profile template into /etc/skel
  become: True
  template:
    src: bash_profile
    dest: /etc/skel/.bash_profile
    owner: root
    group: root
    mode: 0644
    force: yes
