---

- name: Render the discos-addProject template
  template:
    src: discos-addProject
    dest: "/discos/{{ user }}/bin/"
    owner: "{{ user }}"
    group: acs
    mode: 0544
    force: yes
  become: true
  become_user: "{{ user }}"
  when: nis_server_ip is defined


- name: Render the discos-removeProject template
  template:
    src: discos-removeProject
    dest: "/discos/{{ user }}/bin/"
    owner: "{{ user }}"
    group: acs
    mode: 0544
    force: yes
  become: true
  become_user: "{{ user }}"
  when: nis_server_ip is defined


- name: Copy the bashrc template into /etc/skel
  template:
    src: bashrc
    dest: /etc/skel/.bashrc
    owner: root
    group: root
    mode: 0644
    force: yes
  become: true


- name: Copy the bash_profile template into /etc/skel
  template:
    src: bash_profile
    dest: /etc/skel/.bash_profile
    owner: root
    group: root
    mode: 0644
    force: yes
  become: true
