---

- name: Add lustre configuration into modprobe.d
  become: True
  lineinfile:
    path: /etc/modprobe.d/lustre.conf
    line: "options lnet networks=tcp"
    state: present
    create: yes


- name: Check if lustre_client package exists in the local repository
  stat: path={{ local_repository_path }}/{{ lustre_client_file }}
  delegate_to: 127.0.0.1
  register: lustre_client_exists


- name: Download lustre_client package
  get_url:
    validate_certs: no
    url: "{{ lustre_client_url }}"
    dest: "{{ local_repository_path }}/{{ lustre_client_file }}"
  when: lustre_client_exists.stat.exists == False
  delegate_to: 127.0.0.1


- name: Check if kmod_lustre_client package exists in the local repository
  stat: path={{ local_repository_path }}/{{ kmod_lustre_client_file }}
  delegate_to: 127.0.0.1
  register: kmod_lustre_client_exists


- name: Download kmod_lustre_client package
  get_url:
    validate_certs: no
    url: "{{ kmod_lustre_client_url }}"
    dest: "{{ local_repository_path }}/{{ kmod_lustre_client_file }}"
  when: kmod_lustre_client_exists.stat.exists == False
  delegate_to: 127.0.0.1


- name: Copy lustre packages to the remote
  become: True
  copy:
    src: "{{ local_repository_path }}/{{ item }}"
    dest: "/tmp/"
  with_items:
    - "{{ kmod_lustre_client_file }}"
    - "{{ lustre_client_file }}"


- name: Install lustre yum packages
  become: True
  yum: name=/tmp/{{ item }} state=present validate_certs=no
  with_items:
    - "{{ kmod_lustre_client_file }}"
    - "{{ lustre_client_file }}"


- name: Delete lustre packages from the remote
  become: True
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - "{{ kmod_lustre_client_file }}"
    - "{{ lustre_client_file }}"


- name: Load lustre modules
  modprobe:
    name: lnet
    state: present


- name: Add lustre modules to startup modules
  become: True
  lineinfile:
    path: /etc/sysconfig/modules/lustre.modules
    line: "{{ item }}"
    state: present
    create: yes
    mode: 0755
  with_items:
    - '#!/bin/sh'
    - ''
    - 'modprobe -v lnet'


- name: Copy the lustre-startup script
  become: True
  template:
    src: lustre-startup
    dest: /usr/bin
    mode: 0755
    force: yes
  when: lustre_network_interface is defined


- name: Execute the lustre-startup script
  become: True
  command: lustre-startup
  when: lustre_network_interface is defined


- name: Add lustre-startup to boot executed scripts
  become: True
  lineinfile:
    path: /etc/rc.d/rc.local
    line: lustre-startup
  when: lustre_network_interface is defined
