---

- name: Set RPCNFSDCOUNT
  replace:
    dest: /etc/sysconfig/nfs
    regexp: '^#RPCNFSDCOUNT=8'
    replace: 'RPCNFSDCOUNT=64'
  become: true


- name: Set idmapd.conf domain
  replace:
    dest: /etc/idmapd.conf
    regexp: '^#Domain = local.domain.edu'
    replace: 'Domain = {{ network_domain_name }}'
  become: true


- name: Create the /exports/home directory
  file:
    path: /exports/home
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes
  become: true


- name: Mount the /home directory into /exports/home
  mount:
    path: /exports/home
    src: /home
    fstype: ext4
    opts: bind
    state: mounted

    
- name: Configure /etc/exports
  lineinfile:
    path: /etc/exports
    state: present
    line: "{{ item }}"
  with_items:
    - "exports          {{ network_ip_address }}(ro,no_subtree_check,fsid=0,crossmnt)"
    - "/exports/home    {{ network_ip_address }}(rw,no_subtree_check,no_root_squash)"
  become: true


- name: Start rpcbind service
  service:
    name: rpcbind
    state: started
    enabled: yes


- name: Start rpcidmapd service
  service:
    name: rpcidmapd
    state: started
    enabled: yes


- name: Start nfs service
  service:
    name: nfs
    state: started
    enabled: yes
