---

- name: Enable home directory automatic generation
  command: "authconfig --enablemkhomedir --update"
  become: true


- name: Start rcpbind service
  service:
    name: rpcbind
    state: started
    enabled: yes


- name: Start ypbind service
  service:
    name: ypbind
    state: started
    enabled: yes
