---

###############
# ACS Variables
###############

acs_tag: 'ACS-FEB2017'
acssw: /alma/{{ acs_tag }}/ACSSW

cdb_versions: ['SRT', 'Medicina', 'Noto']

acs_dest: { file: 'acs-2017-02-binaries-64bit.tar.bz2' }
extprod_dest: { file: 'extprod-2017-02-binaries-64bit.tar.bz2' }


###############################
# DISCOS Dependencies Variables
###############################

cfitsio: { file: 'cfitsio3370.tar.gz', build_dir: 'cfitsio' }
ccfits: { file: 'CCfits-2.4.tar.gz', build_dir: 'CCfits' }
fv: { file: 'fv5.4_pc_linux64.tar.gz' }
modbus: { file: 'libmodbus-3.0.6.tar.gz', build_dir: 'libmodbus-3.0.6' }
f2c: { file: 'f2c.zip'}

googletest_repo: "447d58b4ee8ea96b4757a5bb5f0b3be75af6c2a1"
googletest_build_dir: "googletest-{{ googletest_repo }}"
googletest_file: "{{ googletest_build_dir }}.zip"
gmock_build: "{{ remote_build_path }}/{{ googletest_build_dir }}/googlemock"
gtest_build: "{{ remote_build_path }}/{{ googletest_build_dir }}/googletest"

qt_version: qt-4.5.2
qt_lib: /usr/local/{{ qt_version }}
qt_build_dir: qt-x11-opensource-src-4.5.2
qt_file: "{{ qt_build_dir}}.tar.gz"

sip_build_dir: sip-4.19.2
sip_file: "{{ sip_build_dir }}.tar.gz"

pyqt_build_dir: PyQt4_gpl_x11-4.12
pyqt_file: "{{ pyqt_build_dir }}.tar.gz"

pyqwt_build_dir: PyQwt-5.2.0
pyqwt_file: "{{ pyqwt_build_dir }}.tar.gz"

slalibrary_file: "SlaLibrary.tar.gz"


#######################
# IUS Release Variables
#######################

ius_release: { file: 'ius-release-el7.rpm' }


################
# Misc Variables
################

monitor_receivers: False
