name: DISCOS provisioning and deployment on Docker container

on:
  workflow_dispatch:
  push:

jobs:
  provision:
    env:
      REPOSITORY_TOKEN: "${{ secrets.DEPENDENCIES_TOKEN }}"
    runs-on: ubuntu-latest
    steps:
      - name: Free up space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3'
          check-latest: true
      - name: Install package and dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r test_requirements.txt
          pip install .
      - name: Provision the container
        run: |
          if [[ "$RUNNER_DEBUG" == "1" ]]; then
            discos-deploy manager:development --docker --default-passwords -v
          else
            discos-deploy manager:development --docker --default-passwords
          fi
      - name: Shutdown the container
        run: |
          docker stop manager
      - name: Show container status
        if: always()
        run: |
          docker ps -a || true
      - name: Show container logs
        if: always()
        run: |
          docker logs manager || true
