name: DISCOS provisioning and deployment on Docker container

on:
  workflow_dispatch:
  push:

jobs:
  provision:
    env:
      REPOSITORY_TOKEN: "${{ secrets.DEPENDENCIES_TOKEN }}"
      GH_TOKEN: "${{ secrets.GH_WORKFLOWS_TOKEN }}"
      GOOGLE_DRIVE_TOKEN: "${{ secrets.GOOGLE_DRIVE_TOKEN }}"
      PROVISIONED_CONTAINER_GDRIVE_ID: "${{ secrets.PROVISIONED_CONTAINER_GDRIVE_ID }}"
    runs-on: ubuntu-latest
    steps:
      - name: Free up space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - name: Clone the repository
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3'
          check-latest: true
      - name: Install package and dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r test_requirements.txt
          pip install .
      - name: Provision the container
        run: |
          if [[ "$RUNNER_DEBUG" == "1" ]]; then
            discos-deploy manager:development --docker --default-passwords -v
          else
            discos-deploy manager:development --docker --default-passwords
          fi
      - name: Save provisioned image as tar artifact
        run: |
          discos-container save discos_manager.tar
        working-directory: /home/runner
      - name: Shutdown the container
        if: always()
        run: |
          discos-container stop || true
      - name: Upload the Docker image to Google Drive
        run: |
          pip install -r .github/utils/gdrive_requirements.txt
          python .github/utils/upload_to_gdrive.py
          gh secret set GOOGLE_DRIVE_TOKEN --org discos --visibility selected --repos discos,deployment < token.json
